---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passengerfrontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: passengerfrontend
    spec:
      containers:
      - name: passengerfrontend
        image: sarahjessiman/passengerfrontend:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: frontendUrl
          value: http://passengerfrontend
  selector:
    matchLabels:
      app: passengerfrontend
---
apiVersion: v1
kind: Service
metadata:
  name: passengerfrontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: passengerfrontend